name: Terraform-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_MODULE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_MODULE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_MODULE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_MODULE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_MODULE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_MODULE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_MODULE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_MODULE_TENANT_ID }}

    steps:
      - name: Clone repo
        uses: actions/checkout@main

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        
      - name: Install Inspec 
        uses: actionshub/chef-install@1.1.0

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      #### Basic Tests
      - name: Terraform Init Basic
        id: init_basic
        run: | 
          cd tests/basic
          terraform init

      - name: Terraform Plan Basic
        id: plan_basic
        run: | 
          cd tests/basic
          terraform plan
          
      - name: Terraform Apply Basic
        id: apply_basic
        run: | 
          cd tests/basic
          terraform apply --auto-approve

      - name: Inspec Scan Basic
        id: inspec_basic
        run: | 
          inspec exec tests/basic/azure-inspec-tests --chef-license accept -t azure://
        continue-on-error: false

      - name: Terraform Destroy Basic
        id: destroy_basic
        run: | 
          cd tests/basic
          terraform destroy --auto-approve


      #### Advanced Tests
      - name: Terraform Init Advanced
        id: init_advanced
        run: | 
          cd tests/advanced
          terraform init

      - name: Terraform Plan Advanced
        id: plan_advanced
        run: | 
          cd tests/advanced
          terraform plan
          
      - name: Terraform Apply Advanced
        id: apply_advanced
        run: | 
          cd tests/advanced
          terraform apply --auto-approve

      - name: Inspec Scan Advanced
        id: inspec_advanced
        run: | 
          inspec exec tests/advanced/azure-inspec-tests --chef-license accept -t azure://
        continue-on-error: false

      - name: Terraform Destroy Advanced
        id: destroy_advanced
        run: | 
          cd tests/advanced
          terraform destroy --auto-approve
